DROP TABLE IF EXISTS STOCK;

CREATE TABLE STOCK(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
STOCK_NUMBER VARCHAR(255),
STOCK_NAME VARCHAR(255),
PRICE VARCHAR(255),
PURCHASE_DATE DATE,
QUANTITY INT
);